### PR TITLE
compare  style and layout change

### PR DESCRIPTION
**Pull request by lucyzsunshine**
compare  1) change layout, 2) change compare section layout; 3) change style and horizontally to vertically

### CODE REVIEW

**Comment by rcavezza** [comment]
Can you add some screenshots please? Hard to visualize without pulling down.

**Comment by lucyzsunshine** [comment]
> 

Screenshot 2023-04-23 at 10 29 34 PM
Screenshot 2023-04-25 at 6 11 01 PM
Screenshot 2023-04-25 at 6 11 19 PM
Screenshot 2023-04-25 at 6 11 30 PM

**Comment by lucyzsunshine** [comment]
add title
Screenshot 2023-04-25 at 11 18 09 PM

**Comment by rcavezza** [comment]
👍 Any thoughts on having some type of outline in between the compared sections of the 3 drugs? On a quick glance, it's a little difficult to distinguish where one ends and one begins.

**Review by rcavezza — APPROVED** [review]
One small comment/suggestion, but should be good otherwise.

**Comment by ColeDCrawford** [comment]
Yeah, maybe just an `<hr>` or add some styling to the bottom of the div or whatever containing element there is to differentiate?

Think that making the titles bold might be nice too. Probably could get rid of the space after them to more closely join the title + text, right now you could read it as 6 separate paragraphs.

I think that the drugs titles at the top of the page could be better formatted still rather than just a column of bold text. We could use cards and a flexbox container? They don't have to match the vertical layout of the sections, so don't be constrained by that.

**Pull request merged**
