### PR TITLE
change style sheet, design, logo, front end

### PR DESCRIPTION
**Pull request by lucyzsunshine**
test the new name works

### CODE REVIEW

**Comment by ColeDCrawford** [comment]
Can you please use semantic, useful names for PRs and branches? Describe what it does and why you are opening the PR.

**Comment by lucyzsunshine** [comment]
@ColeDCrawford Please review, thx cole

**Comment by rcavezza** [comment]
@lucyzsunshine Can you throw some screenshots in the description please? I don't plan on pulling this down locally to check out how it renders.

**Comment by lucyzsunshine** [comment]
> @lucyzsunshine Can you throw some screenshots in the description, please? I don't plan on pulling this down locally to check out how it renders.
I add it in JIRA, by feature: [JIRA](https://cscie599-drug-labels.atlassian.net/jira/software/c/projects/DL/boards/1/backlog?view=detail&selectedIssue=DL-143&quickFilter=2&issueLimit=100). not able to add image here.

**Review by agiannini — APPROVED** [review]

**Pull request merged**
