### PR TITLE
Meta section categories

### PR DESCRIPTION
**Pull request by ColeDCrawford**

### CODE REVIEW

**Comment by ColeDCrawford** [comment]
Migrations still needed, that's why the tests are failing

**Comment by ColeDCrawford** [comment]
This migration is slow, maybe 20-30 minutes to run

**Comment by ColeDCrawford** [comment]
@KingYiuWoo this passed! If you could try running it that would be cool.

**Comment by KingYiuWoo** [comment]
image
Loaded some FDA labels. Seem to be working fine

**Pull request merged**
