### PR TITLE
Direct match style

### PR DESCRIPTION
**Pull request by lucyzsunshine**
label search results style

### CODE REVIEW

**Comment by lucyzsunshine** [comment]
update direct match, for toggle. since the search kit lib call of js changes in search item radio selection, if change style here, the js selection actually can not be called in js lib, ( see ref in const radioGroup = document.getElementsByName("search-type");radioGroup.forEach(function(radio) )
so just simply add a toolkit hint instead of changing the CSS, HTML, and whole js calling search kit lib

**Comment by ColeDCrawford** [comment]
I don't understand what you mean by you can't update the style because of the Javascript? That's just wrong. As long as you don't change the `name` attribute of the `input` elements it works exactly the same. Otherwise if you need a different element, change the JS selector?

**Comment by lucyzsunshine** [comment]
done ~.~ 
Screenshot 2023-04-30 at 12 21 31 PM

**Comment by lucyzsunshine** [comment]
@ColeDCrawford review required

**Review by ColeDCrawford — COMMENTED** [review]
Was thinking something [more like this](https://codepen.io/nindev/pen/BaapjEN) which I linked before? It looks like you took those styles but didn't finish applying them? Probably best practice to cite the code as well ...

**Comment by lucyzsunshine** [comment]
> Was thinking something [more like this](https://codepen.io/nindev/pen/BaapjEN) which I linked before? It looks like you took those styles but didn't finish applying them? Probably best practice to cite the code as well ...

I tried, but the style looks very "ios" and the whole feeling kinda not match what we have now on the page, I prefer the current look, but for sure- will "cite"

**Review by ColeDCrawford — APPROVED** [review]
Ok. If you're not planning to use the styles which you added, please remove them, no need to add CSS you're not actually using. Feel free to merge after that.

**Comment by lucyzsunshine** [comment]
> Ok. If you're not planning to use the styles which you added, please remove them, no need to add CSS you're not actually using. Feel free to merge after that.

right, will clean up~

**Comment by lucyzsunshine** [comment]
1) update the style of a single-page view
2) label search results style
3) update label result page style
4) change style search type choices style
5) clean up, cite, change color to fill the consistent tone with other component design

**Pull request merged**
